version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-auv9m84u2zvq"
s3_prefix = "hello-world"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Name=\"hello-world\" Environment=\"test\""
image_repositories = []
